[project]
name = "tiptoi-dl"
version = "0.1.1"
description = "A TipToi Download helper"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "coloredlogs>=15.0.1",
    "psutil>=7.1.0",
    "requests>=2.32.5",
    "tqdm>=4.67.1",
]

[project.scripts]
tiptoi-dl = "tiptoidl:main"
