name: Generate TipToi catalog

on:
  workflow_dispatch:
  schedule:
    - cron:  '30 18 * * *'

permissions:
  contents: read
  pages: write      # to deploy to Pages
  id-token: write   # to verify the deployment originates from an appropriate source

concurrency:
  group: "pages"
  cancel-in-progress: false


jobs:
  generate-catalog:
    name: generate catalog
    runs-on: ubuntu-latest
    
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Scrape products
        run: |
          uv run python .github/scripts/generate.py

      - name: list files
        run: ls -la

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './output'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 


